global:
  scrape_interval: 5s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: krakend
    static_configs:
      - targets: ['krakend_ce:9091']
  - job_name: users-service
    static_configs:
      - targets: ['users_service:8080']
  - job_name: wishlists-service
    static_configs:
      - targets: ['wishlists_service:8080']
